translator.microsoft.resourceKey=92aaa6c93572c458981e2a525525d87cf
translator.microsoft.region=eastasia
translator.microsoft.endpoint=https://api.cognitive.microsofttranslator.com

translator.youDao.appKey=6282a2e351655a62e
translator.youDao.appSecret=t2Hjd1QpoUQ3WdCv3e2HY83TmgA1rTUUB
translator.youDao.url=https://openapi.youdao.com/api

translator.baidu.appId=220240706002093065
translator.baidu.appSecret=W29AI8ZYseayDe0k2XTAc