CREATE TABLE `biz_base_factory` (
  `id` int(11) NOT NULL COMMENT 'ID',
  `code` varchar(32) NOT NULL COMMENT '工厂编号',
  `name` varchar(64) DEFAULT NULL COMMENT '工厂名称',
  `maintainer` varchar(128) DEFAULT NULL,
  `maintaintime` datetime DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL COMMENT '地址',
  `country` varchar(64) DEFAULT NULL COMMENT '国家',
  `province` varchar(32) DEFAULT NULL COMMENT '省',
  `industry` varchar(32) DEFAULT NULL COMMENT '行业类别',
  `contact` varchar(255) DEFAULT NULL COMMENT '联系人',
  `contactphone` varchar(32) DEFAULT NULL COMMENT '联系手机',
  `longitude` varchar(32) DEFAULT NULL COMMENT '经度',
  `latitude` varchar(32) DEFAULT NULL COMMENT '纬度',
  `note` varchar(255) DEFAULT NULL COMMENT '备注',
  `delflag` int(11) DEFAULT '0',
  `DefaultLang` varchar(32) DEFAULT NULL,
  `creator` varchar(128) DEFAULT NULL,
  `createtime` datetime DEFAULT NULL,
  `scode` varchar(64) DEFAULT NULL,
  `3rdFlag` varchar(32) DEFAULT NULL COMMENT '第三方推送工厂',
  `version` varchar(32) DEFAULT NULL,
  `datagettype` varchar(12) DEFAULT NULL COMMENT '数据采集方式 DataGetType',
  `status` varchar(32) DEFAULT 'fsValid',
  `city` varchar(64) DEFAULT NULL COMMENT '城市',
  `ExpireDate` date DEFAULT NULL COMMENT '失效日期',
  `Industrysize` varchar(32) DEFAULT NULL COMMENT '行业规模',
  `PurchasePeriod` int(11) DEFAULT NULL COMMENT '购买年限',
  `filename` varchar(64) DEFAULT NULL COMMENT 'logo',
  `aliasName` varchar(128) DEFAULT NULL COMMENT '生产中心别名',
  `EffectDate` date DEFAULT NULL COMMENT '生效日期',
  PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='工厂'
